name: Cleanup Old Development Images

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

env:
  IMAGE_NAME: podmortem/podmortem-ai-interface

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete old development images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.IMAGE_NAME }}
          package-type: 'container'
          min-versions-to-keep: 20
          ignore-versions: '^(v\d+\.\d+\.\d+.*|latest|deps-cache)$'
          token: ${{ secrets.GITHUB_TOKEN }}
