name: Cleanup Old Development Images

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

env:
  IMAGE_NAME: podmortem-ai-interface

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete old development images
        uses: windyakin/delete-package-versions-keep-latest@v1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          package-name: ${{ env.IMAGE_NAME }}
          keep-latest-package-versions: 20
          token: ${{ secrets.GITHUB_TOKEN }}
